/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search
     * @description Search across both holdings (top10) and entities (holder_companies).
     *
     *     Companies hit either source (holdings has detailed timeline, holder_companies
     *     has whole-market teamwork coverage). People come from holder_companies only,
     *     since that's where we have the cleaner is_person='个人' filter.
     */
    get: operations["search_api_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/person/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Person Detail */
    get: operations["person_detail_api_person__name__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/person/{name}/disambiguate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Disambiguate */
    get: operations["disambiguate_api_person__name__disambiguate_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/company/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Company Detail */
    get: operations["company_detail_api_company__code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/network": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Network */
    get: operations["network_api_network_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/discover/top-cross-holders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Top Cross Holders
     * @description High-frequency cross-company individual shareholders.
     *
     *     Source: `holder_companies` (whole-market coverage from teamwork ETL).
     *     `total_value` is enriched from holdings × latest close when available.
     */
    get: operations["top_cross_holders_api_discover_top_cross_holders_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/discover/top-coholder-pairs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Top Coholder Pairs */
    get: operations["top_coholder_pairs_api_discover_top_coholder_pairs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/annotation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Annotations */
    get: operations["list_annotations_api_annotation_get"];
    put?: never;
    /** Create Annotation */
    post: operations["create_annotation_api_annotation_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AnnotationRequest */
    AnnotationRequest: {
      /**
       * Op
       * @enum {string}
       */
      op: "merge" | "split" | "bind_qid" | "is_person";
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /**
       * User
       * @default anonymous
       */
      user: string;
    };
    /** AnnotationResponse */
    AnnotationResponse: {
      /** Id */
      id: number;
      /**
       * Op
       * @enum {string}
       */
      op: "merge" | "split" | "bind_qid" | "is_person";
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** User */
      user: string;
      /** Ts */
      ts: string;
    };
    /** BucketMeta */
    BucketMeta: {
      /** Bucket Idx */
      bucket_idx: number;
      /** Size */
      size: number;
      /**
       * Level
       * @enum {string}
       */
      level: "high" | "mid" | "low" | "single";
      /** Label */
      label: string;
      /** Evidence */
      evidence: string;
      /** Total Buckets */
      total_buckets: number;
    };
    /** BucketSummary */
    BucketSummary: {
      /** Bucket Idx */
      bucket_idx: number;
      /** Size */
      size: number;
      /**
       * Level
       * @enum {string}
       */
      level: "high" | "mid" | "low" | "single";
      /** Label */
      label: string;
      /** Evidence */
      evidence: string;
      /** Top Peers */
      top_peers: string[];
      /** Companies */
      companies: string[];
    };
    /** CoholderPair */
    CoholderPair: {
      /** Holder A */
      holder_a: string;
      /** Holder B */
      holder_b: string;
      /** Co Count */
      co_count: number;
      /** Company List */
      company_list: string;
    };
    /** CoholderSummary */
    CoholderSummary: {
      /** Name */
      name: string;
      /** Co Count */
      co_count: number;
      /** Is Person */
      is_person: boolean;
    };
    /** CompanyDetail */
    CompanyDetail: {
      /** Stock Code */
      stock_code: string;
      /** Stock Name */
      stock_name: string;
      /** Available Dates */
      available_dates: string[];
      /** Current Date */
      current_date: string | null;
      /** Top10 */
      top10: components["schemas"]["Top10Row"][];
      /** Stack Series */
      stack_series: components["schemas"]["StackSeriesPoint"][];
    };
    /** CompanyHolding */
    CompanyHolding: {
      /** Stock Code */
      stock_code: string;
      /** Stock Name */
      stock_name: string;
      /** Report Date */
      report_date: string;
      /** Rank */
      rank: number;
      /** Holdings */
      holdings: number;
      /** Pct Total */
      pct_total?: number | null;
      /** Pct Free */
      pct_free?: number | null;
      /** Holdings Value */
      holdings_value?: number | null;
      /** Source Table */
      source_table: string;
    };
    /** CrossHolder */
    CrossHolder: {
      /** Holder Name */
      holder_name: string;
      /** N Companies */
      n_companies: number;
      /** Companies */
      companies: components["schemas"]["CrossHolderCompany"][];
      /** Total Value */
      total_value?: number | null;
    };
    /** CrossHolderCompany */
    CrossHolderCompany: {
      /** Stock Code */
      stock_code: string;
      /** Stock Name */
      stock_name: string;
      /** Pct Total */
      pct_total?: number | null;
      /** Holdings */
      holdings: number;
    };
    /** DisambiguateResponse */
    DisambiguateResponse: {
      /** Name */
      name: string;
      /** Total Companies */
      total_companies: number;
      /** Total Buckets */
      total_buckets: number;
      /** Multi Company Buckets */
      multi_company_buckets: number;
      /** Singletons */
      singletons: number;
      /** Buckets */
      buckets: components["schemas"]["BucketSummary"][];
      /** Singletons Preview */
      singletons_preview: components["schemas"]["SingletonPreview"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
      /** Databases */
      databases: {
        [key: string]: boolean;
      };
    };
    /** NetworkEdge */
    NetworkEdge: {
      /** Source */
      source: string;
      /** Target */
      target: string;
      /** Weight */
      weight: number;
      /** Kind */
      kind: string;
    };
    /** NetworkNode */
    NetworkNode: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Kind */
      kind: string;
      /** Is Person */
      is_person?: boolean | null;
      /** Hop */
      hop: number;
    };
    /** NetworkResponse */
    NetworkResponse: {
      /** Focus */
      focus: string;
      /** Nodes */
      nodes: components["schemas"]["NetworkNode"][];
      /** Edges */
      edges: components["schemas"]["NetworkEdge"][];
      stats: components["schemas"]["NetworkStats"];
    };
    /** NetworkStats */
    NetworkStats: {
      /** N Nodes */
      n_nodes: number;
      /** N Edges */
      n_edges: number;
      /** Truncated */
      truncated: boolean;
    };
    /** PersonDetail */
    PersonDetail: {
      /** Name */
      name: string;
      /**
       * Data Source
       * @enum {string}
       */
      data_source: "entity" | "raw_name" | "annotated";
      bucket_meta?: components["schemas"]["BucketMeta"] | null;
      wikidata?: components["schemas"]["WikidataProfile"] | null;
      /** Companies */
      companies: components["schemas"]["CompanyHolding"][];
      /** Total Value Series */
      total_value_series: components["schemas"]["TotalValuePoint"][];
      /** Coholders */
      coholders: components["schemas"]["CoholderSummary"][];
    };
    /** SearchCompany */
    SearchCompany: {
      /** Stock Code */
      stock_code: string;
      /** Stock Name */
      stock_name: string;
    };
    /** SearchPerson */
    SearchPerson: {
      /** Name */
      name: string;
      /** N Companies */
      n_companies?: number | null;
    };
    /** SearchResponse */
    SearchResponse: {
      /** People */
      people: components["schemas"]["SearchPerson"][];
      /** Companies */
      companies: components["schemas"]["SearchCompany"][];
    };
    /** SingletonPreview */
    SingletonPreview: {
      /** Bucket Idx */
      bucket_idx: number;
      /** Stock Code */
      stock_code: string;
      /** Stock Name */
      stock_name: string;
    };
    /** StackSeriesPoint */
    StackSeriesPoint: {
      /** Date */
      date: string;
      /** Holder Name */
      holder_name: string;
      /** Holdings */
      holdings: number;
      /** Holdings Value */
      holdings_value?: number | null;
    };
    /** Top10Row */
    Top10Row: {
      /** Rank */
      rank: number;
      /** Holder Name */
      holder_name: string;
      /** Share Type */
      share_type?: string | null;
      /** Holdings */
      holdings: number;
      /** Pct */
      pct?: number | null;
      /** Pct Field */
      pct_field: string;
      /** Change Value */
      change_value?: string | null;
      /** Change Pct */
      change_pct?: number | null;
      /** Is Person */
      is_person: boolean;
      /** Source Table */
      source_table: string;
      /** Holdings Value */
      holdings_value?: number | null;
    };
    /** TotalValuePoint */
    TotalValuePoint: {
      /** Date */
      date: string;
      /** Value */
      value: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WikidataProfile */
    WikidataProfile: {
      /** Name */
      name: string;
      /** Qid */
      qid?: string | null;
      /** Label */
      label?: string | null;
      /** Description */
      description?: string | null;
      /** Birth */
      birth?: string | null;
      /** Occupations */
      occupations?: string | null;
      /** Employer */
      employer?: string | null;
      /** Zh Wiki */
      zh_wiki?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  search_api_search_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  person_detail_api_person__name__get: {
    parameters: {
      query?: {
        bucket?: number | null;
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  disambiguate_api_person__name__disambiguate_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DisambiguateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  company_detail_api_company__code__get: {
    parameters: {
      query?: {
        date?: string | null;
      };
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanyDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  network_api_network_get: {
    parameters: {
      query: {
        focus: string;
        hops?: number;
        min_pct?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NetworkResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  top_cross_holders_api_discover_top_cross_holders_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CrossHolder"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  top_coholder_pairs_api_discover_top_coholder_pairs_get: {
    parameters: {
      query?: {
        limit?: number;
        min_co?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CoholderPair"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_annotations_api_annotation_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnnotationResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_annotation_api_annotation_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnnotationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnnotationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
